In [15]:
import TF_input_pipeline 

In [16]:
import numpy as np

In [17]:
import time

In [18]:
import tensorflow as tf

In [19]:
import datetime

In [20]:
import NN_tensorflow
import TF_input_pipeline
import tensorflow as tf
import numpy as np

In [21]:
import os

In [83]:
model = NN_tensorflow.TF_Model(name="Test Model")
model.layers_from_json("G2Net_Detecting_Continuous_Gravitational_Waves_Layers.json")

Metrics = NN_tensorflow.tf_Metrics()
Metrics.from_JSON(path="DCGW_Metrics_Params.json")

model.add_optimizer(NN_tensorflow.tf_optimizer(name="Adam", type="Adam", params={"learning_rate": 0.0001}))
model.add_loss(
    NN_tensorflow.tf_loss(
        name="MAE", type="BinaryCrossentropy", params={"label_smoothing": 0.1, "from_logits": False}
    )
)
model.add_metrics(Metrics)

dataset = TF_input_pipeline.TF_Dataset()

dataset.from_json("DCGW_train_params.json")


In [84]:
dataset.build()


XTrain Loading
yTrain Loading


In [86]:
dataset.yDATA_train

array([ 1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  0,  1,  0,  1,  1,  1,
        1,  1,  1,  0,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,
        1,  1,  0,  0,  1,  1,  1,  0,  0,  0,  0,  1,  1,  0,  0,  0,  1,
        1,  1,  1,  0,  0,  0,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  0,
        1,  0,  1,  1,  0,  0,  0,  1,  1,  0,  1,  1,  1,  0,  1,  1,  1,
        1,  1,  1,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,
        1,  1,  1,  1,  0,  1,  1,  0,  0,  0,  0,  1,  1,  1,  0,  0,  1,
        0,  1,  0,  1,  0,  0,  0,  1,  0,  0,  1,  0,  1,  0,  1,  1,  1,
        1,  1,  0,  1,  0,  1,  0,  1,  0,  0,  1,  1,  1,  1,  0,  1,  1,
        1,  0,  1,  1,  0,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  0,  1,  0,  1,  1,  0,  1,  1,  1,  0,  0,  1,
        1,  1,  1,  0,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  0,  0,  0,
        1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  0,  1,  1,  0,  1,  1,  1,
        0,  0,  0,  1,  0

In [87]:
self = dataset

In [88]:
self.index_train = [x for x in self.Xindex_train if self.yindex_train]

In [89]:
self.index_train == self.Xindex_train 

True

In [98]:
print("XFilter")
self.index_train = [x for x in self.Xindex_train if self.yindex_train]
clean_XDATA_train = []
clean_yDATA_train = []
for i in range(len(self.XDATA_train)):
    if self.Xindex_train[i] in self.index_train:
        clean_XDATA_train.append([self.Xindex_train[i],self.XDATA_train[i]])

for i in range(len(self.yDATA_train)):
    if self.yindex_train[i] in self.index_train:
        clean_yDATA_train.append([self.yindex_train[i],self.yDATA_train[i]])

        
clean_XDATA_train = [x for i, x in sorted(clean_XDATA_train)]
clean_yDATA_train = [x for i, x in sorted(clean_yDATA_train)]
clean_XDATA_train = np.array(clean_XDATA_train,dtype=np.float32)
clean_yDATA_train = np.array(clean_yDATA_train,dtype=np.float32)
self.XDATA_train = clean_XDATA_train
self.yDATA_train = clean_yDATA_train

XFilter


In [96]:
clean_XDATA_train = []
clean_yDATA_train = []
for i in range(len(self.XDATA_train)):
    if self.Xindex_train[i] in self.index_train:
        clean_XDATA_train.append([self.Xindex_train[i],self.XDATA_train[i]])

for i in range(len(self.yDATA_train)):
    if self.yindex_train[i] in self.index_train:
        clean_yDATA_train.append([self.yindex_train[i],self.yDATA_train[i]])

In [100]:
px.histogram(self.yDATA_train)

In [99]:
clean_yDATA_train

array([1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0.,
       0., 0., 1., 0., 1.

In [82]:
self.XDATA_train

array([[[[-2.01780108e-24,  1.70660666e-22,  1.64324296e-22,
          -3.14728175e-23],
         [-1.87113869e-22,  1.00735020e-22,  5.36462208e-23,
           2.11682052e-22],
         [-1.90160601e-22,  1.52689834e-22, -1.53539232e-23,
          -1.04387313e-22],
         ...,
         [-8.01955113e-23,  5.76858513e-23,  1.54795525e-23,
          -5.64928033e-23],
         [ 1.49911681e-22, -7.36853073e-23, -7.05851849e-23,
          -2.31085095e-23],
         [-1.40711818e-23, -1.13303486e-22, -1.07662638e-22,
          -7.20162874e-24]],

        [[-1.73556609e-23,  5.82527141e-23, -2.66208496e-23,
          -4.15750302e-23],
         [-1.94014171e-23, -9.85744810e-23,  1.22438609e-22,
          -5.41714823e-23],
         [-5.79111247e-23,  1.26377776e-22,  1.59083836e-22,
          -1.75652881e-22],
         ...,
         [-7.38728858e-23, -8.07863428e-23,  1.78712816e-22,
           1.62983838e-22],
         [-6.06779691e-23,  1.98590419e-22,  3.87294007e-23,
          -5.192216

In [76]:
clean_yDATA_train

[]

In [72]:
clean_XDATA_train

[['001121a05',
  array([[[-2.01780108e-24,  1.70660666e-22,  1.64324296e-22,
           -3.14728175e-23],
          [-1.87113869e-22,  1.00735020e-22,  5.36462208e-23,
            2.11682052e-22],
          [-1.90160601e-22,  1.52689834e-22, -1.53539232e-23,
           -1.04387313e-22],
          ...,
          [-8.01955113e-23,  5.76858513e-23,  1.54795525e-23,
           -5.64928033e-23],
          [ 1.49911681e-22, -7.36853073e-23, -7.05851849e-23,
           -2.31085095e-23],
          [-1.40711818e-23, -1.13303486e-22, -1.07662638e-22,
           -7.20162874e-24]],
  
         [[-1.73556609e-23,  5.82527141e-23, -2.66208496e-23,
           -4.15750302e-23],
          [-1.94014171e-23, -9.85744810e-23,  1.22438609e-22,
           -5.41714823e-23],
          [-5.79111247e-23,  1.26377776e-22,  1.59083836e-22,
           -1.75652881e-22],
          ...,
          [-7.38728858e-23, -8.07863428e-23,  1.78712816e-22,
            1.62983838e-22],
          [-6.06779691e-23,  1.98590419e-

In [57]:
dataset.filter()

XFilter


In [28]:
file = np.load("D:/dataset_padded/XTRAIN.npz")

In [31]:
len(file["index"])

600

In [34]:
import pandas as pd

In [35]:
label = pd.read_csv("C:/Users/trisr/Desktop/deepl/DATA/train_labels.csv")

In [38]:
new_label = label[label["id"].isin(file["index"])]

In [54]:
len(dataset.XDATA_train)


600

In [55]:
len(dataset.yDATA_train)


603

In [58]:
dataset.yDATA_train

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,
        1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,
        1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,
        1.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,
        1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,
        0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,
        1.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  0

In [42]:
import git
def get_git_root(path=os.getcwd()):
    git_repo = git.Repo(path, search_parent_directories=True)
    git_root = git_repo.git.rev_parse("--show-toplevel")
    return git_root
git_root = get_git_root()

xparams_train = {
    "PATH": git_root + "/DATA/",
    "MODE": "npz",
    "METHOD": "full",
    "OUTPUT": git_root + "/dataset_padded/",
}

yparams_train = {
    "PATH": git_root + "/DATA/train_labels.csv",
    "MODE": "csv",
    "COL": "target",
    "INDEX": "id",
    "METHOD": "full",
}


xparams = {}
yparams = {}
xparams["TRAIN"] = xparams_train
yparams["TRAIN"] = yparams_train
xpreprocess = {"HDF5_GW_detection": None}
ypreprocess = {"type_transform": tf.float32}
xpreprocess = None
ypreprocess = None

dataset = TF_input_pipeline.TF_Dataset(
    xparams=xparams, yparams=yparams, xpreprocess=xpreprocess, ypreprocess=ypreprocess,
)


In [43]:
dataset.build()

XTrain Loading
yTrain Loading


In [11]:
import plotly.express as px

In [40]:
new_label

id  target
0    001121a05       1
1    004f23b2d       1
2    00a6db666       1
3    00f36a6ac       1
4    010a387db       1
..         ...     ...
598  fe38dbe64       1
599  feafd0d16       1
600  feeca844e       1
601  ff5ad023f       1
602  ffa1d19c7       1

[600 rows x 2 columns]

In [41]:
px.histogram(new_label["target"])

# Sample

In [11]:
def downsampling(train_data, params):
    def convert_timestamp(seq):
        rep =[]
        for time in np.array(seq):
            rep.append(datetime.datetime.fromtimestamp(time / 1e3))
        rep=np.array(rep)
        return rep
    
    def calculte_step(train_data,size):
        reptime1=[]
        reptime2=[]
        for x in  dataset.XDATA_train:
            key =list(x.keys())[0]
            rep =[]
            for time in np.array(x[key]["H1"]["timestamps_GPS"]):
                rep.append(datetime.datetime.fromtimestamp(time / 1e3))
            rep=np.array(rep)
            reptime1.append(rep)

            rep =[]
            for time in np.array(x[key]["L1"]["timestamps_GPS"]):
                rep.append(datetime.datetime.fromtimestamp(time / 1e3))
            rep=np.array(rep)
            reptime2.append(rep)

        freq1=[]
        for x in reptime1:
            freq1.append((x[len(x)-1]-x[0])/size)

        freq2=[]
        for x in reptime2:
            freq2.append((x[len(x)-1]-x[0])/size)
        step1 = np.mean(freq1)
        step2 = np.mean(freq2)
        step = np.mean([step1,step2])
        return step
    
    def mask_creation(size,step):
        return [
        i*step for i in range(size)    
        ]

    def downsample_index(timestamp,mask):
        timestamp = timestamp-timestamp[0]
        index = []
        for value in mask :
            diff=abs(timestamp-value)
            ind = np.argmin(diff)
            index.append(ind)
        return index
    
    def extract_downsampling(x,downsample_index):
        rep = []
        downsample_index = np.sort(downsample_index)
        for value in x:
            row=[]
            for ind in downsample_index:
                row.append(value[ind])
            rep.append(row)
        rep=np.array(rep)
        return rep

    def x_procress(x,mask):
        key = list(x.keys())[0]
        x0 = np.real(np.array(x[key]["H1"]["SFTs"]))
        x1 = np.imag(np.array(x[key]["H1"]["SFTs"]))
        x2 = np.real(np.array(x[key]["L1"]["SFTs"]))
        x3 = np.imag(np.array(x[key]["L1"]["SFTs"]))
        
        time0_1 = convert_timestamp(x[key]["H1"]["timestamps_GPS"])
        index0_1 = downsample_index(time0_1,mask)
        time2_3 = convert_timestamp(x[key]["L1"]["timestamps_GPS"])
        index2_3 = downsample_index(time2_3,mask)
        x0 = extract_downsampling(x0, index0_1)
        x0 = np.transpose(x0)
        x1 = extract_downsampling(x1, index0_1)
        x1 = np.transpose(x1)
        x2 = extract_downsampling(x2, index2_3)
        x2 = np.transpose(x2)
        x3 = extract_downsampling(x3, index2_3)
        x3 = np.transpose(x3)
        return (x0, x1, x2, x3, key)

    def preprocessing(data):
        step = calculte_step(train_data,params["SIZE"])
        mask = mask_creation(params["SIZE"],step)
        rep_dataset = []
        # os.makedirs(params["PATH"], exist_ok=True)
        for i in range(len(data)):
            x = data[i]
            x_map = np.zeros((params["SIZE"], 360, 4))
            (x0, x1, x2, x3, key) = x_procress(x, mask)
            x_map[:, :, 0] = x0
            x_map[:, :, 1] = x1
            x_map[:, :, 2] = x2
            x_map[:, :, 3] = x3
            rep_dataset.append(x_map)
        return rep_dataset

    return preprocessing

params = {"SIZE":1024}
preprocessing = downsampling(dataset.XDATA_train, params)
t0=time.time()
data_sampled = preprocessing(dataset.XDATA_train)
t1=time.time()
print("Time",t1-t0)

Time 1032.4482746124268


# Moyennage

In [ ]:
def agglomeration(train_data, params):
    def convert_timestamp(seq):
        rep =[]
        for time in np.array(seq):
            rep.append(datetime.datetime.fromtimestamp(time / 1e3))
        rep=np.array(rep)
        return rep
    
    def calculte_step(train_data,size):
        reptime1=[]
        reptime2=[]
        for x in  dataset.XDATA_train:
            key =list(x.keys())[0]
            rep =[]
            for time in np.array(x[key]["H1"]["timestamps_GPS"]):
                rep.append(datetime.datetime.fromtimestamp(time / 1e3))
            rep=np.array(rep)
            reptime1.append(rep)

            rep =[]
            for time in np.array(x[key]["L1"]["timestamps_GPS"]):
                rep.append(datetime.datetime.fromtimestamp(time / 1e3))
            rep=np.array(rep)
            reptime2.append(rep)

        freq1=[]
        for x in reptime1:
            freq1.append((x[len(x)-1]-x[0])/size)

        freq2=[]
        for x in reptime2:
            freq2.append((x[len(x)-1]-x[0])/size)
        step1 = np.mean(freq1)
        step2 = np.mean(freq2)
        step = np.mean([step1,step2])
        return step
    
    def mask_creation(size,step):
        return [
        i*step for i in range(size)    
        ]

    def downsample_index(timestamp,mask):
        timestamp = timestamp-timestamp[0]
        index = []
        for value in mask :
            diff=abs(timestamp-value)
            ind = np.argmin(diff)
            index.append(ind)
        return index
    
    def compact_timeseries(x,downsample_index,func):
        rep = []
        downsample_index = np.sort(downsample_index)
        for value in x:
            row=[]
            for i in range(len(downsample_index)-1):
                row.append(func(value[downsample_index[i]:(downsample_index[i+1])]))
            row.append(func(value[downsample_index[-1]:]))
            rep.append(np.array(row))
        rep=np.array(rep)
        return rep

    def x_procress(x,mask,params):
        key = list(x.keys())[0]
        x0 = np.real(np.array(x[key]["H1"]["SFTs"]))
        x1 = np.imag(np.array(x[key]["H1"]["SFTs"]))
        x2 = np.real(np.array(x[key]["L1"]["SFTs"]))
        x3 = np.imag(np.array(x[key]["L1"]["SFTs"]))
        
        time0_1 = convert_timestamp(x[key]["H1"]["timestamps_GPS"])
        index0_1 = downsample_index(time0_1,mask)
        time2_3 = convert_timestamp(x[key]["L1"]["timestamps_GPS"])
        index2_3 = downsample_index(time2_3,mask)
        x0 = compact_timeseries(x0, index0_1,params["FUNC"])
        x0 = np.transpose(x0)
        x1 = compact_timeseries(x1, index0_1,params["FUNC"])
        x1 = np.transpose(x1)
        x2 = compact_timeseries(x2, index2_3,params["FUNC"])
        x2 = np.transpose(x2)
        x3 = compact_timeseries(x3, index2_3,params["FUNC"])
        x3 = np.transpose(x3)
        return (x0, x1, x2, x3, key)

    def preprocessing(data):
        step = calculte_step(train_data,params["SIZE"])
        mask = mask_creation(params["SIZE"],step)
        rep_dataset = []
        # os.makedirs(params["PATH"], exist_ok=True)
        for i in range(len(data)):
            x = data[i]
            x_map = np.zeros((params["SIZE"], 360, 4))
            (x0, x1, x2, x3, key) = x_procress(x, mask,params)
            x_map[:, :, 0] = x0
            x_map[:, :, 1] = x1
            x_map[:, :, 2] = x2
            x_map[:, :, 3] = x3
            rep_dataset.append(x_map)
        return rep_dataset

    return preprocessing

params = {"SIZE":1024,"FUNC":np.mean}
preprocessing = agglomeration(dataset.XDATA_train, params)
t0=time.time()
data_mean = preprocessing(dataset.XDATA_train)
t1=time.time()
print("Time",t1-t0)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:188: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)


(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)
(1024, 360, 4)


# Interpolation

In [ ]:
def interpolation(train_data, params):
    def convert_seq(seq):
        rep=seq-seq[0]
        return rep
    
    def interpolate_timeseries(y,index,mask,type):
        f = interpolate.interp1d(index, y,kind=type)
        return f(mask)
    

    def x_procress(x,mask,params):
        key = list(x.keys())[0]
        x0 = np.real(np.array(x[key]["H1"]["SFTs"]))
        x1 = np.imag(np.array(x[key]["H1"]["SFTs"]))
        seq01 = convert_seq((x[key]["H1"]["timestamps_GPS"])
        x2 = np.real(np.array(x[key]["L1"]["SFTs"]))
        x3 = np.imag(np.array(x[key]["L1"]["SFTs"]))
        seq23 = convert_seq((x[key]["L1"]["timestamps_GPS"])

        
        x0 = interpolate_timeseries(x0,
                                         seq01,
                                         mask,
                                         params["TYPE"])
        x0 = np.transpose(x0)
        x1 = interpolate_timeseries(x1,
                                 seq01,
                                 mask,
                                 params["TYPE"])
        x1 = np.transpose(x1)
                            
        x2 = interpolate_timeseries(x2,
                                 seq23,
                                 mask,
                                 params["TYPE"])
        x2 = np.transpose(x2)
        x3 = interpolate_timeseries(x3,
                                 seq23,
                                 mask,
                                 params["TYPE"])
        x3 = np.transpose(x3)
        return (x0, x1, x2, x3, key)

    def preprocessing(data):
        step = calculte_step(train_data,params["SIZE"])
        mask = mask_creation(params["SIZE"],step)
        rep_dataset = []
        # os.makedirs(params["PATH"], exist_ok=True)
        for i in range(len(data)):
            x = data[i]
            x_map = np.zeros((params["SIZE"], 360, 4))
            (x0, x1, x2, x3, key) = x_procress(x, mask,params)
            x_map[:, :, 0] = x0
            x_map[:, :, 1] = x1
            x_map[:, :, 2] = x2
            x_map[:, :, 3] = x3
            rep_dataset.append(x_map)
        return rep_dataset

    return preprocessing

params = {"SIZE":1024,"TYPE":"quadratic"}
preprocessing = interpolation(dataset.XDATA_train, params)
t0=time.time()
data_interpolated = preprocessing(dataset.XDATA_train)
t1=time.time()
print("Time",t1-t0)

In [ ]:
f = interpolate.interp1d(x, y)

In [ ]:
xnew = np.arange(0, 9, 0.1)
ynew = f(xnew)   # use interpolation function returned by `interp1d`

In [21]:
X=[]
for x in size2:
    X.append(x[1])

In [22]:
np.max(X)

4817

In [20]:
np.max(X)

4843

In [10]:
length

4647

In [11]:
diff_full=[]
for x in reptime2:
    diff_full.append((x[len(x)-1]-x[0]))

diff=[]
for x in reptime2:
    for i in range(len(x)-1):
        diff.append((x[i+1]-x[i]))

value = []
for x in reptime2:
    for y in x:
        value.append(y)

minival= np.min(value) 
step = np.mean(diff)
length = int(np.max(diff_full)/(np.mean(diff)))+1

for x in reptime2:
    mask_x = [
        np.min(x) + i*step for i in range(length)    
    ]

In [12]:
length

4653

In [ ]:
mask

In [ ]:
np.max(diff_full)/(np.mean(diff2)/2)

In [ ]:
np.mean(diff2)

In [ ]:
np.mean(X)

In [ ]:
max(X)

In [ ]:
reptime1=np.array(reptime1)

In [ ]:
reptime2=np.array(reptime2)

In [ ]:
datetime.timedelta(seconds=60)

In [ ]:
(x[i+1]-x[i]).seconds

In [ ]:
datetime.timedelta(seconds=0)<(x[i+1]-x[i])<datetime.timedelta(seconds=60)

In [ ]:
x[i]

In [ ]:
x[i+1]

In [ ]:
np.min(diff)

In [ ]:
x = dataset.XDATA_train[0]

In [ ]:
np.array(x["001121a05"]["H1"]["SFTs"]).shape

In [ ]:
len(x["001121a05"]["H1"]["SFTs"][0])

In [ ]:
x["001121a05"]["H1"]['timestamps_GPS']

In [ ]:
x["001121a05"]["L1"].keys()

In [ ]:
x["001121a05"]["L1"]["SFTs"]

In [ ]:
your_timestamp = np.array(x["001121a05"]["L1"]['timestamps_GPS'])

In [ ]:
for time in  np.array(x["001121a05"]["L1"]['timestamps_GPS']):
    print(datetime.datetime.fromtimestamp(time / 1e3))

In [ ]:
import datetime
your_timestamp = 1331856000000
date = datetime.datetime.fromtimestamp(your_timestamp / 1e3)

In [ ]:
date = datetime.datetime.fromtimestamp(your_timestamp / 1e3)

In [ ]:
date

In [ ]:
x["001121a05"]["frequency_Hz"]